apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: render-assets-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxx
  directoryPerms: "750"
  gidRangeStart: "2000"
  gidRangeEnd: "4000"
  uid: "1000"
  gid: "1000"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
