apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rendering
resources:
  - ../../base
  - storageclass-local.yaml
  - pv-local.yaml
patchesStrategicMerge:
  - patch-configmap.yaml
images:
@@
images:
  - name: ghcr.io/company/spot-render-api
    newName: local/spot-render-api
    newTag: latest
  - name: ghcr.io/company/spot-render-worker
    newName: local/spot-render-worker
    newTag: latest
