apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spot-render-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/raafa001/spot-render.git
    targetRevision: main
    path: k8s/overlays/prd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rendering
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
