apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: render-db
  namespace: rendering
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: spotrender-secrets
    kind: ClusterSecretStore
  target:
    name: render-db
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: /spot-render/database
        property: host
    - secretKey: password
      remoteRef:
        key: /spot-render/database
        property: password
