apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: render-api
  namespace: rendering
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - rendering
  selector:
    matchLabels:
      app.kubernetes.io/name: render-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
