name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Nome do ambiente
        type: string
        required: true
        default: prd

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:
  apply:
    name: Apply infra/terraform
    runs-on: ubuntu-latest
    environment:
      name: platform-infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform apply
        working-directory: infra/terraform
        env:
          TF_VAR_environment: ${{ inputs.environment }}
        run: terraform apply -auto-approve
